# /// script
# dependencies = [
#   "requests",
# ]
# ///
#!/usr/bin/env python3
"""
Reprocessor — Re-query Registration & ICE for Human-Corrected Spreadsheets
==========================================================================
Standalone tool that reads a CSV generated by the ALPR pipeline (after a
human has reviewed and corrected plate numbers / states), requeries the
registration databases and ICE database, and writes a new CSV with updated
columns.

Usage:
    python reprocessor/reprocessor.py <path_to_csv>

The input file is updated in-place with refreshed registration and ICE data.
"""

import csv
import json
import os
import sys
import time
import urllib.parse
import urllib.request

try:
    import requests
except ImportError:
    print("[ERROR] The 'requests' library is required. Install with: pip install requests")
    sys.exit(1)

# ── State Name → Code Normalization ──────────────────────────────────────────
STATE_CODES = {
    "alabama": "AL", "alaska": "AK", "arizona": "AZ", "arkansas": "AR",
    "california": "CA", "colorado": "CO", "connecticut": "CT", "delaware": "DE",
    "florida": "FL", "georgia": "GA", "hawaii": "HI", "idaho": "ID",
    "illinois": "IL", "indiana": "IN", "iowa": "IA", "kansas": "KS",
    "kentucky": "KY", "louisiana": "LA", "maine": "ME", "maryland": "MD",
    "massachusetts": "MA", "michigan": "MI", "minnesota": "MN",
    "mississippi": "MS", "missouri": "MO", "montana": "MT", "nebraska": "NE",
    "nevada": "NV", "new hampshire": "NH", "new jersey": "NJ",
    "new mexico": "NM", "new york": "NY", "north carolina": "NC",
    "north dakota": "ND", "ohio": "OH", "oklahoma": "OK", "oregon": "OR",
    "pennsylvania": "PA", "rhode island": "RI", "south carolina": "SC",
    "south dakota": "SD", "tennessee": "TN", "texas": "TX", "utah": "UT",
    "vermont": "VT", "virginia": "VA", "washington": "WA",
    "west virginia": "WV", "wisconsin": "WI", "wyoming": "WY",
}


def normalize_state(raw: str) -> str:
    """Accept a 2-letter code or full state name and return a 2-letter code."""
    if not raw:
        return ""
    cleaned = raw.strip()
    if len(cleaned) == 2 and cleaned.isalpha():
        return cleaned.upper()
    lower = cleaned.lower()
    return STATE_CODES.get(lower, cleaned.upper()[:2])


def clean_plate(raw: str) -> str:
    """Strip spaces, dashes, tabs, and uppercase a plate string, then remove known OCR hallucinations."""
    import re
    cleaned = raw.replace(" ", "").replace("-", "").replace("\t", "").upper().strip()
    # IL: FP prefix before 4-7 digits
    match = re.match(r'^FP(\d{4,7})$', cleaned)
    if match:
        return match.group(1)
    # WI: FP suffix after standard plate characters
    match = re.match(r'^([A-Z]{2,4}\d{3,4})FP$', cleaned)
    if match:
        return match.group(1)
    return cleaned


# ── .env Loader ──────────────────────────────────────────────────────────────
def _load_env_key(key_name: str) -> str:
    """Read a KEY=value entry from .env."""
    # Walk up from the reprocessor dir to find the project root .env
    cfg = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), ".env")
    if os.path.exists(cfg):
        with open(cfg) as f:
            for line in f:
                line = line.strip()
                if line.startswith(f"{key_name}="):
                    return line[len(key_name) + 1:].strip()
    return ""


# ── PlateToVin API Keys (round-robin rotation) ──────────────────────────────
_ptv_raw = os.environ.get("PLATETOVIN_API_KEYS") or _load_env_key("PLATETOVIN_API_KEYS")
_PTV_KEYS: list[str] = [k.strip() for k in _ptv_raw.split(",") if k.strip()] if _ptv_raw else []
_ptv_key_index = 0
if not _PTV_KEYS:
    print("[WARNING] No PlateToVin API keys found. Registration lookups will fail.")


# ── Registration Lookup: PlateToVin ──────────────────────────────────────────
def lookup_platetovin(plate: str, state: str) -> dict:
    """Look up ANY US plate via PlateToVin commercial API with round-robin key rotation."""
    global _ptv_key_index

    if not _PTV_KEYS:
        return {"registration_found": False, "desc": "PlateToVin keys not configured", "vin": "", "title": ""}

    clean = plate.replace(" ", "").replace("-", "").upper()
    clean_state = state.upper() if state and len(state) == 2 else ""

    for _ in range(len(_PTV_KEYS)):
        key = _PTV_KEYS[_ptv_key_index % len(_PTV_KEYS)]
        try:
            resp = requests.post(
                "https://platetovin.com/api/convert",
                headers={"Authorization": key, "Content-Type": "application/json", "Accept": "application/json"},
                json={"plate": clean, "state": clean_state},
                timeout=10
            )
            if resp.status_code == 404:
                return {"registration_found": False, "desc": "registration not found", "vin": "", "title": ""}
            if resp.status_code in (401, 402, 403, 429) or resp.status_code >= 500:
                print(f"\n      [PlateToVin] Key {_ptv_key_index % len(_PTV_KEYS)} rejected (HTTP {resp.status_code}), rotating...")
                _ptv_key_index += 1
                continue
            if resp.status_code != 200:
                return {"registration_found": False, "desc": f"PlateToVin HTTP {resp.status_code}", "vin": "", "title": ""}
            data = resp.json()
            if not data.get("success"):
                msg = data.get("error") or data.get("message") or ""
                if any(kw in msg.lower() for kw in ["invalid", "unauthorized", "quota", "limit", "auth"]):
                    print(f"\n      [PlateToVin] Key {_ptv_key_index % len(_PTV_KEYS)} auth error ({msg}), rotating...")
                    _ptv_key_index += 1
                    continue
                return {"registration_found": False, "desc": "registration not found", "vin": "", "title": ""}
            v = data.get("vin") or {}
            if not v:
                return {"registration_found": False, "desc": "registration not found", "vin": "", "title": ""}
            desc = " ".join(x for x in [str(v.get("year", "")), v.get("make", ""), v.get("model", ""), v.get("trim", "")] if x).strip()
            return {"registration_found": True, "desc": desc, "vin": v.get("vin", ""), "title": ""}
        except Exception as e:
            return {"registration_found": False, "desc": f"PlateToVin Error: {e}", "vin": "", "title": ""}

    return {"registration_found": False, "desc": "PlateToVin all keys exhausted", "vin": "", "title": ""}


# ── ICE Lookup (defrostmn.net) ───────────────────────────────────────────────
DEFROST_API_BASE = "https://defrostmn.net/plates/lookup"
DEFROST_PASSWORD = "bCBEYZbpA3"


def lookup_ice(plate: str) -> str:
    """Query defrostmn.net for a single plate. Returns 'Y', 'HS', or 'N'."""
    clean = plate.replace(" ", "").replace("-", "").upper()
    params = urllib.parse.urlencode({"q": clean, "password": DEFROST_PASSWORD})
    url = f"{DEFROST_API_BASE}?{params}"
    headers = {
        "Accept": "application/json",
        "Origin": "https://defrostmn.net",
        "Referer": "https://defrostmn.net/plate-check/",
        "User-Agent": (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/122.0.0.0 Safari/537.36"
        ),
    }
    req = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode("utf-8"))
        matches = data.get("matches", [])
        exact = [m for m in matches if m.get("similarity_score", 0) == 1]
        if not exact:
            return "N"
        status = (exact[0].get("status") or "").strip()
        if status == "Confirmed ICE":
            return "Y"
        elif status == "Highly suspected ICE":
            return "HS"
        else:
            return "N"
    except Exception as e:
        print(f"  [ICE lookup error] {plate}: {e}")
        return "N"


# ── Match Logic ──────────────────────────────────────────────────────────────
def compute_match(make: str, model: str, color: str, reg_desc: str) -> str:
    """Return 'Y' if observed vehicle words overlap registration, else 'N'."""
    obs_words = set(f"{color} {make} {model}".lower().split())
    reg_words = set(reg_desc.lower().split())
    if obs_words & reg_words or any(w in reg_desc.lower() for w in obs_words if len(w) > 3):
        return "Y"
    return "N"


# ── Column Names (from alpr_pipeline.py) ─────────────────────────────────────
COL_PLATE = "Plate"
COL_STATE = "State"
COL_MAKE = "Make"
COL_MODEL = "Model"
COL_COLOR = "Color"
COL_ICE = "ICE"
COL_MATCH = "Match"
COL_REG = "Registration"
COL_VIN = "VIN Associated to Plate (if available)"
COL_TITLE = "Title Issues Associated to VIN (if available)"


def main():
    if len(sys.argv) < 2:
        print("Usage: python reprocessor/reprocessor.py <path_to_csv>")
        sys.exit(1)

    input_path = os.path.abspath(sys.argv[1])
    if not os.path.exists(input_path):
        print(f"[ERROR] File not found: {input_path}")
        sys.exit(1)

    # In-place mode: write back to the same file
    output_path = input_path

    # Read input CSV (handle Excel UTF-8 BOM)
    with open(input_path, "r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        if not reader.fieldnames:
            print("[ERROR] CSV has no header row.")
            sys.exit(1)
        headers = list(reader.fieldnames)
        rows = list(reader)

    print(f"[Reprocessor] Loaded {len(rows)} rows from {os.path.basename(input_path)}")
    print(f"[Reprocessor] Columns: {headers}")
    print()

    # Validate required columns exist
    required = [COL_PLATE, COL_STATE]
    missing = [c for c in required if c not in headers]
    if missing:
        print(f"[ERROR] Missing required columns: {missing}")
        sys.exit(1)

    updated_rows = []
    stats = {"total": 0, "skipped": 0, "reg_found": 0, "reg_not_found": 0,
             "ice_y": 0, "ice_hs": 0, "ice_n": 0}
             
    # Load cache from the same directory as the original batch if available
    target_dir = os.path.dirname(input_path).replace("human", "") or "."
    target_dir = target_dir.replace("MooseReady", "videos/03092026/batch_5")
    cache_file = os.path.join(target_dir, "lookup_cache.json")
    if os.path.exists(cache_file):
        with open(cache_file, "r") as f:
            lookup_cache = json.load(f)
    else:
        lookup_cache = {}

    for i, row in enumerate(rows):
        raw_plate = row.get(COL_PLATE, "").strip()
        raw_state = row.get(COL_STATE, "").strip()

        # Skip empty plates
        if not raw_plate:
            print(f"  [Row {i+1}] Empty plate — skipping.")
            stats["skipped"] += 1
            updated_rows.append(row)
            continue

        plate = clean_plate(raw_plate)
        state = normalize_state(raw_state)
        make = row.get(COL_MAKE, "").strip()
        model = row.get(COL_MODEL, "").strip()
        color = row.get(COL_COLOR, "").strip()

        stats["total"] += 1
        print(f"  [{i+1}/{len(rows)}] {plate} ({state})...", end=" ", flush=True)

        # ── Registration Lookup (PlateToVin) ──────────────────────────────────
        cache_key = f"ptv_{plate}_{state}"
        # Also check legacy cache keys from previous runs
        legacy_key = f"{plate}_{state}"
        vc_legacy_key = f"vc_{plate}_{state}"
        if cache_key in lookup_cache:
            info = lookup_cache[cache_key]
        elif legacy_key in lookup_cache:
            info = lookup_cache[legacy_key]
        elif vc_legacy_key in lookup_cache:
            info = lookup_cache[vc_legacy_key]
        else:
            info = lookup_platetovin(plate, state)
            lookup_cache[cache_key] = info
            with open(cache_file, "w") as f:
                json.dump(lookup_cache, f, indent=2)

        reg_found = info.get("registration_found", False)
        reg_desc = info.get("desc", "") if reg_found else "registration not found"
        vin = info.get("vin", "")
        title = info.get("title", "")

        # ── Match Calculation ────────────────────────────────────────────────
        match_status = ""
        if reg_found:
            match_status = compute_match(make, model, color, reg_desc)
            stats["reg_found"] += 1
        else:
            stats["reg_not_found"] += 1

        # Truncate title to 50 chars
        display_title = title[:47] + "..." if len(title) > 50 else title

        # ── ICE Lookup ───────────────────────────────────────────────────────
        ice_value = lookup_ice(plate)
        if ice_value == "Y":
            stats["ice_y"] += 1
        elif ice_value == "HS":
            stats["ice_hs"] += 1
        else:
            stats["ice_n"] += 1

        # ── Update Row ───────────────────────────────────────────────────────
        # Write back cleaned plate/state and updated lookup columns
        row[COL_PLATE] = plate
        row[COL_STATE] = state
        if COL_REG in row:
            row[COL_REG] = reg_desc
        if COL_VIN in row:
            row[COL_VIN] = vin
        if COL_TITLE in row:
            row[COL_TITLE] = display_title
        if COL_MATCH in row:
            row[COL_MATCH] = match_status
        if COL_ICE in row:
            row[COL_ICE] = ice_value

        status_parts = []
        if reg_found:
            status_parts.append(f"Reg={reg_desc[:40]}")
        else:
            status_parts.append("No reg")
        status_parts.append(f"ICE={ice_value}")
        if match_status:
            status_parts.append(f"Match={match_status}")
        print(" | ".join(status_parts))

        updated_rows.append(row)
        time.sleep(0.5)  # courteous delay between requests

    # ── Write Output CSV ─────────────────────────────────────────────────────
    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        writer.writerows(updated_rows)

    # ── Summary ──────────────────────────────────────────────────────────────
    print()
    print("=" * 60)
    print("REPROCESSOR SUMMARY")
    print("=" * 60)
    print(f"  Input:            {os.path.basename(input_path)}")
    print(f"  Output:           {os.path.basename(output_path)}")
    print(f"  Total rows:       {len(rows)}")
    print(f"  Processed:        {stats['total']}")
    print(f"  Skipped (empty):  {stats['skipped']}")
    print(f"  Reg found:        {stats['reg_found']}")
    print(f"  Reg not found:    {stats['reg_not_found']}")
    print(f"  ICE Y:            {stats['ice_y']}")
    print(f"  ICE HS:           {stats['ice_hs']}")
    print(f"  ICE N:            {stats['ice_n']}")
    print("=" * 60)
    print(f"\n✓ Updated in-place: {output_path}")


if __name__ == "__main__":
    main()
